// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:bershama/models/medicine_model.dart';
import 'package:bershama/models/sale_record.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MedicineModelAdapter());
    registerAdapter(SaleRecordAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MedicineModelAdapter());
    registerAdapter(SaleRecordAdapter());
  }
}
